veterinaria\Bundle\veterinariaBundle\Entity\productos:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombreProd:
            type: string
            length: '30'
        costo:
            type: integer
        precio:
            type: integer
        fechaEntrega:
            type: date
    manyToOne:
        proveedores:
            targetEntity: veterinaria\Bundle\veterinariaBundle\Entity\proveedores
            joinTable:
                name: proveedores_id
                joinColumns:
                    productos_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    proveedores_id:
                        referencedColumnName: id
            mappedBy: productos
        inventario:
            targetEntity: veterinaria\Bundle\veterinariaBundle\Entity\inventario
            joinTable:
                name: inventario_id
                joinColumns:
                    productos_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    inventario_id:
                        referencedColumnName: id
            mappedBy: productos
        ventas:
            targetEntity: veterinaria\Bundle\veterinariaBundle\Entity\ventas
            joinTable:
                name: ventas_id
                joinColumns:
                    ventas_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    productos_id:
                        referencedColumnName: id
            mappedBy: productos
    lifecycleCallbacks: {  }
