medicamentos:
    path:     /
    defaults: { _controller: "veterinariaBundle:medicamentos:index" }

medicamentos_show:
    path:     /{id}/show
    defaults: { _controller: "veterinariaBundle:medicamentos:show" }

medicamentos_new:
    path:     /new
    defaults: { _controller: "veterinariaBundle:medicamentos:new" }

medicamentos_create:
    path:     /create
    defaults: { _controller: "veterinariaBundle:medicamentos:create" }
    methods:  POST

medicamentos_edit:
    path:     /{id}/edit
    defaults: { _controller: "veterinariaBundle:medicamentos:edit" }

medicamentos_update:
    path:     /{id}/update
    defaults: { _controller: "veterinariaBundle:medicamentos:update" }
    methods:  [POST, PUT]

medicamentos_delete:
    path:     /{id}/delete
    defaults: { _controller: "veterinariaBundle:medicamentos:delete" }
    methods:  [POST, DELETE]
