proveedores:
    path:     /
    defaults: { _controller: "veterinariaBundle:proveedores:index" }

proveedores_show:
    path:     /{id}/show
    defaults: { _controller: "veterinariaBundle:proveedores:show" }

proveedores_new:
    path:     /new
    defaults: { _controller: "veterinariaBundle:proveedores:new" }

proveedores_create:
    path:     /create
    defaults: { _controller: "veterinariaBundle:proveedores:create" }
    methods:  POST

proveedores_edit:
    path:     /{id}/edit
    defaults: { _controller: "veterinariaBundle:proveedores:edit" }

proveedores_update:
    path:     /{id}/update
    defaults: { _controller: "veterinariaBundle:proveedores:update" }
    methods:  [POST, PUT]

proveedores_delete:
    path:     /{id}/delete
    defaults: { _controller: "veterinariaBundle:proveedores:delete" }
    methods:  [POST, DELETE]
